import type { Metadata } from 'next'
import StyledComponentsRegistry from "../lib/registry"

import { Amplify } from 'aws-amplify';
import awsExports from '../aws-exports';

export const metadata: Metadata = {
  title: 'Quote Generator',
  description: 'Generated by Raghav for generating random quotes',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body><StyledComponentsRegistry >{children}</StyledComponentsRegistry></body>
    </html>
  )
}
